#codecov:
#  require_ci_to_pass: yes

# 커버리지 상태 관련 설정
coverage:
  status:
    project:
      default:
        target: auto

        branches:
#          - main
#          - dev
          - feature/add-ci