server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monew
    username: ${RDS_NAME_LOCAL}
    password: ${RDS_PASSWORD_LOCAL}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET SESSION hibernate.jdbc.lob.non_contextual_creation=true
  jpa:
    hibernate:
      ddl-auto: update
naver:
  client_id: ${X_Naver_Client_Id}
  client_secret: ${X_Naver_Client_Secret}
logging:
  level:
    root: debug